firewall_uygulama/cApi/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'cApi'

urlpatterns = [
    path('user/', UserView.as_view(), name='user'),
    path('log/', LogView.as_view(), name='log'),
    path('email/', EmailView.as_view(), name='email'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('django_user/', djangoUserView.as_view(), name='django_user'),
]

firewall_uygulama/firewall_uygulama/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework import routers
from cApi import views


router=routers.DefaultRouter()
router.register(r'djangousers', views.djangoUserViewSet, basename='djangousers')
router.register(r'log', views.LogViewSet, basename='log')
router.register(r'email', views.EmailViewSet, basename='email')
router.register(r'user', views.UserViewSet, basename='user')
urlpatterns = router.urls


urlpatterns += [
    path('uygulama/', include('uygulama.urls')),
    path('cApi/', include('cApi.urls')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

firewall_uygulama/uygulama/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'uygulama'

urlpatterns = [
    path('login/', login_view.as_view(), name='login'),
    path('sms/', views.sms, name='sms'),
    path('page/', main_page_view.as_view(), name='page'),
    path('mail/', mail_view.as_view(), name='mail'),
    path('singed_out/', views.SingedOutView.as_view(), name='singed_out'),
    path('send_mail', views.send_mail, name='send_mail'),
]

firewall_uygulama/uygulama/models.py
from django.db import models



# Create your models here.
class User(models.Model):  # User model
    name = models.CharField(max_length=40,  default="null")
    surname = models.CharField(max_length=40,  default="null")
    tc_no = models.CharField(max_length=11,  default="null")
    birth_date = models.CharField(max_length=4, default="null")
    tel_no = models.CharField(max_length=11, default="null")
    confirmation = models.BooleanField()
    email = models.CharField(max_length=40, default="null")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.tc_no


class Sms(models.Model):  # Sms model
    sms_code = models.CharField(max_length=8, default="null")
    confirmation = models.BooleanField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Sms'

    def __str__(self):
        return self.sms_code


class email_verification(models.Model):  # Email model
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="null")
    email_code = models.CharField(max_length=6)
    confirmation = models.BooleanField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Email'

    def __str__(self):
        return self.email_code


class Log(models.Model):  # Log model
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="null")
    sms = models.ForeignKey(Sms, on_delete=models.CASCADE, default="null")
    email_ver = models.ForeignKey(email_verification, on_delete=models.CASCADE, default="null")
    timestamp = models.DateTimeField(auto_now_add=True)
    ip_tables = models.CharField(max_length=40, default='null')

    class Meta:
        verbose_name_plural = 'Log'

    def __str__(self):
        return self.ip_tables

firewall_uygulama/uygulama/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View, generic

from .models import User, Log, email_verification
from dotenv import load_dotenv

from .utils.kps_api import *
from .utils.mailgun_api import send_simple_message
from .utils.user_settings import *


from .login_form import LoginForm
from .email_form import MailForm

load_dotenv()

PORT = os.environ.get("PORT")
IFACE = os.environ.get("IFACE")
IP_ADDRESS = os.environ.get("IP_ADDRESS")


class login_view(View):

    def get(self, request):
        form = LoginForm()
        return render(request, 'uygulama/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            global name, email, data
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            tc_no = form.cleaned_data['tc_no']
            birth_date = form.cleaned_data['birth_date']
            tel_no = form.cleaned_data['tel_no']
            email = form.cleaned_data['email']
            confirmation = kps(name, surname, tc_no, birth_date)  # KPS API doğrulaması
            data = User(name=name, surname=surname, tc_no=tc_no, birth_date=birth_date, tel_no=tel_no,
                        confirmation=confirmation, email=email)
            data.save()
            if confirmation:  # KPS API doğrulaması başarılı
                global otp
                otp = send_simple_message(email)  # Mail API mesaj gönder
                return redirect('uygulama:mail')  # mail sayfasına yönlendir
            else:
                return HttpResponse('<b> Hatalı Kimlik Bilgisi Girişi </b>')  # KPS API doğrulaması başarısız
        return render(request, 'uygulama/login.html', {'form': form})


class mail_view(View):
    def get(self, request):
        form = MailForm()
        return render(request, 'uygulama/mail.html', {'form': form})

    def post(self, request):
        form = MailForm(request.POST)
        if form.is_valid():
            otp_verification = request.POST['otp']
            if otp == otp_verification:  # SMS API doğrulama
                global verification_data, ipaddress
                verification_data = email_verification(user=data, email_code=otp, confirmation=True)
                verification_data.save()  # email doğrulama kodu doğruysa veritabanına kaydet
                ipaddress = get_ip()
                request.session['logged_in'] = True
                give_permission(
                    ipaddress)  # internet varsa session oluştur //oluşturulmadı sadece iptables ayarları var
                return redirect('uygulama:page')
            else:
                return HttpResponse('<b> Hatalı Doğrulama Kod Girişi </b>')
        return render(request, 'uygulama/mail.html', {'form': form})


class main_page_view(generic.TemplateView):  # main sayfa (tüm verification başarılı olursa yönlendirilecek sayfa)
    template_name = 'uygulama/page.html'

    def get(self, request, *args, **kwargs):
        if request.session.get('logged_in'):
            log = Log(user=data, email_ver=verification_data, ip_tables=ipaddress)
            log.save()
            return render(request, self.template_name, {'name': name})
        else:
            return redirect('uygulama:login')


class SingedOutView(generic.TemplateView):  # logout sayfası
    template_name = 'uygulama/singed_out.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        request.session['logged_in'] = False  # session silinir
        logout(ipaddress)
        return render(request, self.template_name)


def send_mail(request):  # SEND AGAIN MAIL
    global otp
    otp = send_simple_message(email)
    return redirect('uygulama:mail')


# sendgrid twilio api çöp olduğu için mailgun api kullanıldı
def sms(request):
    return "<h1> SMS API </h1>"


"""    if request.method == 'POST':
        otp_verification = request.POST['otp']
        if otp == otp_verification:
            ipaddress = get_ip()
            give_permission(ipaddress)
            return redirect(request, 'uygulama:page')
        else:
            return 'Hatalı Kod Girişi'
    return render(request, 'uygulama/sms.html')
"""

firewall_uygulama/uygulama/templates/uygulama/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
  	<title>Login</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="{% static 'https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap' %}" rel="stylesheet">

	<link rel="stylesheet" href="{% static  'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>

	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Captive Portal</h2>
				</div>
			</div>
		<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">

						<h3 class="text-center mb-4">Login Page</h3>
							<form  action="{% url 'uygulama:login' %} " method="POST" class="login-form"
							style="{display:flex; flex-direction:column}">
							{% csrf_token %}



		      					<div class="form-group">
								{{ form }}
		      					</div>
	           				 <div class="form-group">
	          				  	<button id="login" type="submit" class="form-control btn btn-primary rounded submit px-3">Login</button>
							 </div>

	          				</form>
	        		</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

firewall_uygulama/uygulama/templates/uygulama/mail.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
  	<title>Mail</title>
	  {% csrf_token %}  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="{% static 'https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap' %}" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Captive Portal</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">

		      	<h3 class="text-center mb-4">Mail Verification</h3>
						<form action="{% url 'uygulama:mail' %}" method="post" class="login-form">
							{% csrf_token %}

		      		<div class="form-group">
						{{form}}		      		
					</div>
	            <div class="form-group">
	            	<button id="verification_button" type="submit" class="form-control btn btn-primary rounded submit px-3">Onayla</button>
	            </div>
				
	           
				<div class="form-group d-md-flex">
									<a href="{% url 'uygulama:send_mail' %}">Send Again?</a>
	            </div>

	          </form>


	        </div>
				</div>
			</div>
		</div>

	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

firewall_uygulama/uygulama/templates/uygulama/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Giriş</title>
</head>
<body>
							{% csrf_token %}
    <p>Welcome, {{ name }}. Thanks for logging in. </p>
    <p><a href="{% url 'uygulama:singed_out' %}">Logout</a></p>


</body>
</html>

firewall_uygulama/uygulama/templates/uygulama/singed_out.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>

<section id="page" class="">
  <p>You are signed out!</p>

  <p>Click <a href="{% url 'uygulama:login' %}">here</a> to sign in again.</p>
</section>
</body>
</html>

firewall_uygulama/uygulama/templates/uygulama/sms.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
  	<title>SMS</title>
	  {% csrf_token %}  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="{% static 'https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap' %}" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Captive Portal</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap p-4 p-md-5">

		      	<h3 class="text-center mb-4">SMS Verification</h3>
						<form method="post" class="login-form">
		      		<div class="form-group">
		      			<input id="verification_code" type="text" class="form-control rounded-left" placeholder="Sms Code" required>
		      		</div>
	            <div class="form-group">
	            	<button id="verification_button" type="submit" class="form-control btn btn-primary rounded submit px-3">Confirm</button>
	            </div>
				
	           
				<div class="form-group d-md-flex">
									<a href="#">Send Again?</a>
	            </div>

	          </form>


	        </div>
				</div>
			</div>
		</div>

	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>